global:
  scrape_interval: 5s

scrape_configs:
  - job_name: "scheduler-api"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["scheduler-api:8080"]

  - job_name: "scheduler-worker"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["scheduler-worker:8081"]